### ISSUE TITLE
media-libs/quarter: digest verification fails

### ISSUE THREAD

**Issue by waebbl** [Perlovka/portage-overlay#1]
It looks like the cpack subpackage has changed since you last updated the ebuild.
While fetching the sources, the digest verification fails with
```
!!! Fetched file: coin3d-cpack.d-master.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      12582
!!! Expected: 12603
```

It's not even necessary, to download this tarball. I just commented the add_subdirectory line for it and it builds fine without it.

**Comment by Perlovka** [comment]
Thanks for the report, fixed.
BTW, coind3 already made cpack.d optional in their master, so this fix will not be needed for next release.
